# FREEDOM
embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: [0.0, 1.e-04, 1.e-03, 1.e-02]

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: [0.1, 0.3, 0.5]
dropout: [0.6, 0.75, 0.9]

hyper_parameters: ["dropout","reg_weight","mm_image_weight"]
learning_rate_scheduler: [1.0, 50]
learning_rate: 0.001

# training settings
epochs: 1000
stopping_step: 20
train_batch_size: 2048
learner: adam
eval_step: 1
