# LightGCN
embedding_size: 64
n_layers: [1, 2, 3, 4]
reg_weight: [1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06]
hyper_parameters: ["n_layers", "reg_weight"]

learning_rate: 0.001
learning_rate_scheduler: [1.0, 50]

# training settings
epochs: 1000
#learning_rate: 0.001
stopping_step: 10
train_batch_size: 1024
learner: adam
eval_step: 1