# MGCN
embedding_size: 64
n_ui_layers: 2
n_layers: 1

learning_rate_scheduler: [1.0, 50]
lambda_coeff: 0.9
reg_weight: 1.e-04

knn_k: [10,15,20,25,30]

learning_rate: 0.001

cl_loss: [0.001,0.01,0.1]
hyper_parameters: ["cl_loss","knn_k"]

# training settings
epochs: 1000
stopping_step: 20
train_batch_size: 2048
learner: adam
eval_step: 1