# TMLP
embedding_size: 64
feat_embed_dim: 64

reg_weight: 0.0
num_fc_layers: 4
hidden_dim: 512
act_fn: 'tanh'
v_dropout: 0
t_dropout: 0
alpha1: 0.5
tau1: 1
knn_k: 10
n_ui_layers: 2
adj_tensor_path: 'adj_sampling_0.1_5.pt'
mm_image_weight: 0.1
resn_weight: [1.e-5,2.5e-5,5.e-5,1.e-4,2.5e-4,5.e-4,1.e-3,2.5e-3,5.e-3]


learning_rate: 0.001
learning_rate_scheduler: [1.0, 50]
dropout: 0.8
aggr_mode: 'add'

hyper_parameters: ["resn_weight"]

# training settings
epochs: 1000
#learning_rate: 0.001
stopping_step: 20
train_batch_size: 2048
learner: adam
eval_step: 1