# TMLP
embedding_size: 64
feat_embed_dim: 64

reg_weight: 0.0
num_fc_layers: 4
hidden_dim: 512
act_fn: 'tanh'

v_dropout: 0
t_dropout: 0
alpha1: [0.25,0.5,0.75,1.0,1.25,1.5,1.75,2.0]
tau1: 1
knn_k: 10
n_ui_layers: 2
adj_tensor_path: 'adj_sampling_0.1_5.pt'
mm_image_weight: 0.1
rweight: [0.01,0.025,0.05,0.1,0.25,0.5,1.0,2.5,5.0]


learning_rate: 0.001
learning_rate_scheduler: [1.0, 50]
dropout: 0.8
aggr_mode: 'add'

hyper_parameters: ["rweight"]

# training settings
epochs: 1000
#learning_rate: 0.001
stopping_step: 20
train_batch_size: 2048
learner: adam
eval_step: 1